version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ${DB_PATH}:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8060:8080

  node:
    build: ./backend
    restart: always
    ports:
      - 8087:8087
